### ISSUE TITLE
ReadMe File

### ISSUE THREAD

**Issue by T31337** [Oblivionburn/realai#1]
Not Much Info About It,

What Is It/What Does It Do?

Why Not Include A Link To The PlayStore?

Some People Might Also Like A Pre-Compiled APK To Downlaod.

**Comment by Oblivionburn** [comment]
5 minutes of effort on Google can easily answer those questions, and
there's already a pre-compiled apk in the git repo.

http://lmgtfy.com/?q=real+ai+app

http://lmgtfy.com/?q=oblivionburn
