### ISSUE TITLE
Responses get squished off-screen

### ISSUE THREAD

**Issue by LickTheCheese** [Oblivionburn/realai#2]
On my Moto G 2 the new Encourage/Discourage buttons are too big for my screen, and it squishes the replies from the AI completely off the Screen. Could you make the button label's font size smaller or put the `Enter` and `New Session` buttons on the same lines/put the `New Session` and `Menu` buttons on the same line? or have a Option in the Menu to do so? or a option in the Menu to use the old 3 button interface? 
It is kind of annoying to have to close the Virtual keyboard to see what it says, or have to use a bluetooth keyboard on phones with smaller screens.

> Also, this is unrelated, but do you like to have Issues posted Here or on your Forum?

**Comment by Oblivionburn** [comment]
I'll make the font smaller in the next update, hopefully that helps.

I prefer issues to be posted on the Forum... makes it easier to keep up everything if it's centralized in one location.

**Comment by Oblivionburn** [comment]
Did making the button text size smaller help?

**Comment by LickTheCheese** [comment]
Unfortunately, it did not help much, the responses are still pushed off the screen. 2 updates ago, when you put the encourage/discourage buttons to the main screen, did  you add a margin or blank extra line to the reply box? there appears to be some blank space there taking up space.
![screenshot_20180813-152636](https://user-images.githubusercontent.com/30901398/44054294-3512601e-9f10-11e8-93b4-d81f75527f2c.png)

**Comment by Oblivionburn** [comment]
No margins or extra blank lines were added.
Have you tried pressing the back button to dismiss the keyboard?

**Comment by Oblivionburn** [comment]
Ended up just removing the Enter button and moving the New Session button to the Menu. Should be able to see quite a bit more of the output window now.

**Comment by LickTheCheese** [comment]
ok, thanks!
